### ISSUE TITLE
Browserify should output sourcemaps

### ISSUE THREAD

**Issue by geezhawk** [TID-Lab/aggie#220]
Debugging without sourcemaps is really hard. I just built a project with browserify that outputs sourcemaps as well as bundled js, and it speeds production to be able to use the debugger. In that project I used browserify rather than `gulp-browserify`, but I understand that you guys want to start shifting away from the (now deprecated) `gulp-browserify` plugin anyway. If you want I can do a PR that replaces `gulp-browserify` with regular ol' browserify and start generating sourcemaps to speed up the development workflow.

**Comment by pgarrison** [comment]
This is very welcome!
