### ISSUE TITLE
Close Icon does not work on Trash Icon Window Popup

### ISSUE THREAD

**Issue by limmabean** [TID-Lab/aggie#302]
When attempting to delete something using the trash icon, a popup window appears asking to confirm. The button marked cancel cancels the process but the close icon does nothing. 

![CloseWindowNotWorking](https://user-images.githubusercontent.com/25267840/82275297-5e7e7280-9950-11ea-9f66-20647dd0d11a.png)

Can be recreated by clicking the trash icon on a entry and clicking the close icon in the top right of the popup. The window is shown above with the cursor on the close icon. This is true for incidents and users, sources (if you click the delete button), trends (if you click the delete button).

**Comment by karpawich** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Close Icon does not work on Trash Icon Window Popup](https://trello.com/c/63Dmdnq2/48-close-icon-does-not-work-on-trash-icon-window-popup)
