### ISSUE TITLE
When new user is added an error message is shown and user table not automatically updated 

### ISSUE THREAD

**Issue by limmabean** [TID-Lab/aggie#308]
Attempting to add users results in an error message as seen below. 
![Screenshot 2020-05-19 12:46:54](https://user-images.githubusercontent.com/25267840/82354486-db503180-99ce-11ea-9d1b-69bbfbf20878.png)

The user table does not get automatically updated when a new user is added. To see newly added users, the page needs to be reloaded. This means that it seems like adding a user fails (especially considering the error message) but in reality, the user was added and can be confirmed by trying to add a user with the same name. See the error message below. 

![UserIsInDatabase](https://user-images.githubusercontent.com/25267840/82355739-9c22e000-99d0-11ea-9431-0ba494de13b7.png)

**Comment by limmabean** [comment]
This is also related to the defect: Error message when email settings are not configured is useless

To reproduce:
Start Aggie without any email settings
Log in as admin
Go to Settings > Users
Click 'Create User'
Enter a username and valid email
Click 'Submit'
Error alert appears with text 'User failed to be created. Please contact support.'
Instead, it should say something like 'Email settings not configured. Go to Settings > Settings to set a valid security token.'

**Comment by karpawich** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [When new user is added an error message is shown and user table not automatically updated](https://trello.com/c/81NaXCE6/45-when-new-user-is-added-an-error-message-is-shown-and-user-table-not-automatically-updated)
