### ISSUE TITLE
Button to unlink reports from incidents is broken or missing

### ISSUE THREAD

**Issue by limmabean** [TID-Lab/aggie#313]
Controller has the function ready, but there is no button to remove reports from a given incident

**Comment by karpawich** [comment]
I investigated this Issue. There is, in fact, a button to remove reports from a given incident in the **Reports** view from the upper right-hand corner of the Incident section:
![Screenshot from 2020-06-10 14-08-40](https://user-images.githubusercontent.com/34974152/84302957-29ff7000-ab24-11ea-808d-452e3d0ff75e.png)

However, no such button exists in the **Incidents** view:
![Screenshot from 2020-06-10 14-13-39](https://user-images.githubusercontent.com/34974152/84303269-ae51f300-ab24-11ea-8acb-71cbbe947806.png)

I will add functionality to the Incident view that allows a user to select a set of Reports from list at the bottom, and then remove them together via a single button at the top of the list.

**Comment by karpawich** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Button to unlink reports from incidents is missing](https://trello.com/c/BDkWvOzj/44-button-to-unlink-reports-from-incidents-is-missing)
