### ISSUE TITLE
Avoid plaintext storage of HTTPS certificate decryption passphrase on disk

### ISSUE THREAD

**Issue by karpawich** [TID-Lab/aggie#317]
As a temporary fix to get Aggie operational on Node v12, we currently store the passphrase for decryption of the private key (PEM file) used by the Node to start a HTTPS server.

See [this commit](https://github.com/TID-Lab/aggie/pull/299/commits/5c872d935229963d9a50ed18c3616d14ab489230) to see how the temporary fix was implemented.

**Comment by mkyaw6** [comment]
The issue has been fixed and original passphrase prompt behavior has been restored. See [this commit](https://github.com/TID-Lab/aggie/commit/18cb36d1dd6f267ac7154497dc5d3a26cce98b9c) for the fix
