### ISSUE TITLE
HTTPS certificate password prompt entered in plaintext

### ISSUE THREAD

**Issue by karpawich** [TID-Lab/aggie#320]
The HTTPS certificate password is entered via the command line in plaintext. 

## How to reproduce

1. Start up Aggie on your machine with an encrypted `key.pem`
2. Type in the decryption passphrase when prompted by `Enter PEM passphrase:`
3. Observe that the passphrase persists after you submit it by hitting enter.

## Alternatives

- [password-prompt](https://www.npmjs.com/package/password-prompt)
- [read](https://www.npmjs.com/package/read)

Either of these packages come with support for secure password entry, where the password is hidden from view and does not persist after user input.

**Comment by mkyaw6** [comment]
Issue Fixed. See [commit](https://github.com/TID-Lab/aggie/commit/5705439353e8c825d64d8f30731d473ddb3d53f6)
