### ISSUE TITLE
Online demo?

### ISSUE THREAD

**Issue by psegovias** [TID-Lab/aggie#56]
Hi guys, can i see a online demo about this tool? or screenshots?

Regards!

**Comment by psegovias** [comment]
Any news on this?

**Comment by hooverlunch** [comment]
The app has been much improved since we last spoke. There is still no online demo, though. I would encourage you to set up an instance on AWS or similar. The install process is not terribly hard if you have some experience with this kind of thing. Good luck!

**Comment by psegovias** [comment]
Nice! what OS u recommend?

**Comment by hooverlunch** [comment]
Ubuntu 14.04

On Mon, Jul 6, 2015 at 12:08 PM, psegovias <notifications@github.com> wrote:

> Nice! what OS u recommend?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TID-Lab/aggie/issues/56#issuecomment-118911442>.
>



-- 
Tom Smyth

Worker-Owner, Sassafras Tech Collective
Specializing in innovative, usable tech for social change
sassafras.coop *·* @sassafrastech

Resident, Touchstone Cohousing
touchstonecohousing.org

**Comment by psegovias** [comment]
OK, i will install and let you know :)

**Comment by psegovias** [comment]
> aggie@0.4.1 postinstall /home/psegovias/aggie
> node install.js && gulp angular

{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version

/home/psegovias/aggie/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/base.js:246
        throw message;      
              ^
MongoError: Authentication failed.
    at Object.toError (/home/psegovias/aggie/node_modules/mongoose/node_modules/mongodb/lib/mongodb/utils.js:114:11)
    at /home/psegovias/aggie/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1194:31
    at /home/psegovias/aggie/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1903:9
    at Server.Base._callHandler (/home/psegovias/aggie/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)
    at /home/psegovias/aggie/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:487:18
    at MongoReply.parseBody (/home/psegovias/aggie/node_modules/mongoose/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
    at null.<anonymous> (/home/psegovias/aggie/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:445:20)
    at EventEmitter.emit (events.js:95:17)
    at null.<anonymous> (/home/psegovias/aggie/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:207:13)
    at EventEmitter.emit (events.js:98:17)
    at Socket.<anonymous> (/home/psegovias/aggie/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:440:22)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:746:14)
    at Socket.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
    at emitReadable (_stream_readable.js:404:5)
npm ERR! weird error 8
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! not ok code 0

**Comment by hooverlunch** [comment]
Not sure about this one. Looks like your DB authentication is failing. Try
upgrading Mongoose?

On Mon, Jul 6, 2015 at 4:28 PM, psegovias <notifications@github.com> wrote:

> aggie@0.4.1 postinstall /home/psegovias/aggie
> node install.js && gulp angular
>
> { [Error: Cannot find module '../build/Release/bson'] code:
> 'MODULE_NOT_FOUND' }
> js-bson: Failed to load c++ bson extension, using pure JS version
>
>
> /home/psegovias/aggie/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/base.js:246
> throw message;
>
> ^
> MongoError: Authentication failed.
> at Object.toError
> (/home/psegovias/aggie/node_modules/mongoose/node_modules/mongodb/lib/mongodb/utils.js:114:11)
> at
> /home/psegovias/aggie/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1194:31
> at
> /home/psegovias/aggie/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1903:9
> at Server.Base.
>
>
>
>
>
>
>
>
>
>
> *callHandler
> (/home/psegovias/aggie/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)
> at
> /home/psegovias/aggie/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:487:18
> at MongoReply.parseBody
> (/home/psegovias/aggie/node_modules/mongoose/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
> at null.
> (/home/psegovias/aggie/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:445:20)
> at EventEmitter.emit (events.js:95:17) at null.
> (/home/psegovias/aggie/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:207:13)
> at EventEmitter.emit (events.js:98:17) at Socket.
> (/home/psegovias/aggie/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:440:22)
> at Socket.EventEmitter.emit (events.js:95:17) at Socket.
> (_stream_readable.js:746:14) at Socket.EventEmitter.emit (events.js:92:17)
> at emitReadable* (_stream_readable.js:408:10)
> at emitReadable (_stream_readable.js:404:5)
> npm ERR! weird error 8
> npm WARN This failure might be due to the use of legacy binary "node"
> npm WARN For further explanations, please read
> /usr/share/doc/nodejs/README.Debian
>
> npm ERR! not ok code 0
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TID-Lab/aggie/issues/56#issuecomment-118988328>.
>



-- 
Tom Smyth

Worker-Owner, Sassafras Tech Collective
Specializing in innovative, usable tech for social change
sassafras.coop *·* @sassafrastech

Resident, Touchstone Cohousing
touchstonecohousing.org

**Comment by psegovias** [comment]
Already fixed :+1:
